server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://;serverName=azure-server-demo-robles.database.windows.net;databaseName=azure-db-dem-robles;encrypt=true
    username: projects-javareact-admin
    password: JorKIdo23@
#    username: ${MART_USERNAME}
#    password: ${MART_PASSWORD}